### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Boutry** [janicicpredrag/Larus#6]
The following line triggers the error "z3/CSP solver not found in the PATH!" even when z3 is present in the path when timeout is not (I fixed it by installing coreutils using brew: brew install coreutils).

https://github.com/janicicpredrag/Larus/blob/444e26835e51a8b22158a5e6e29bf8195fbe732c/ProvingEngine/NewSMT_Engine/SMT_ProvingEngine.cpp#L1336

**Comment by janicicpredrag** [comment]
Indeed.  The message 
      cout << endl << "z3/CSP solver not found in the PATH!" << endl << flush;
replaced by
      cout << endl << "z3/CSP solver or the 'timeout' command not found in the PATH!" << endl << flush;
